export interface MinimalTemplateDef {
  id: string;
  name: string;
  category: string;
  description: string;
  badge: string;
  bgClass: string;
  cardClass: string;
  primaryBtnClass: string;
  accentTextClass: string;
  headerStyle: string;
  fontStyle: string;
}

export const MINIMAL_TEMPLATES: MinimalTemplateDef[] = [
  {
    id: "obrador-tradicional",
    name: "Obrador Tradicional",
    category: "Panadería & Obrador",
    description: "Tonos arpillera y masa madre cálidos con estética de panadería artesanal de pueblo.",
    badge: "Más Popular",
    bgClass: "bg-[#faf6f0] text-[#3e2723]",
    cardClass: "bg-[#fffdfa] border-[#e0d6c8] shadow-sm hover:border-[#b18e69]",
    primaryBtnClass: "bg-[#8d6e63] text-white hover:bg-[#6d4c41] shadow-md shadow-[#8d6e63]/20",
    accentTextClass: "text-[#8d6e63]",
    headerStyle: "from-[#8d6e63] to-[#5d4037]",
    fontStyle: "font-serif",
  },
  {
    id: "boutique-clean",
    name: "Boutique Minimalista",
    category: "Moda & Gourmet",
    description: "Diseño monocromo sobrio, líneas delgadas y tipografía elegante.",
    badge: "Elegante",
    bgClass: "bg-[#f8f9fa] text-[#212529]",
    cardClass: "bg-white border-[#e9ecef] shadow-xs hover:border-[#212529]",
    primaryBtnClass: "bg-[#212529] text-white hover:bg-[#000000]",
    accentTextClass: "text-[#212529]",
    headerStyle: "from-[#212529] to-[#343a40]",
    fontStyle: "font-sans tracking-wide",
  },
  {
    id: "mercado-fresco",
    name: "Mercado Local Fresco",
    category: "Frutas & Proximidad",
    description: "Verde botánico y blanco limpio para productos ecológicos y de huerta.",
    badge: "Eco / Proximidad",
    bgClass: "bg-[#f4f8f5] text-[#1b4332]",
    cardClass: "bg-white border-[#d8f3dc] shadow-sm hover:border-[#40916c]",
    primaryBtnClass: "bg-[#2d6a4f] text-white hover:bg-[#1b4332] shadow-md shadow-[#2d6a4f]/20",
    accentTextClass: "text-[#2d6a4f]",
    headerStyle: "from-[#2d6a4f] to-[#1b4332]",
    fontStyle: "font-sans",
  },
  {
    id: "express-mobile",
    name: "Express Mobile 1-Tap",
    category: "Pedidos Rápido",
    description: "Botones gigantes de 1-tap, alto contraste, enfocado a pedidos veloces en smartphone.",
    badge: "Ultra Rápido",
    bgClass: "bg-[#111827] text-white",
    cardClass: "bg-[#1f2937] border-[#374151] shadow-lg hover:border-[#f59e0b]",
    primaryBtnClass: "bg-[#f59e0b] text-gray-900 font-extrabold hover:bg-[#d97706] shadow-lg shadow-[#f59e0b]/30",
    accentTextClass: "text-[#f59e0b]",
    headerStyle: "from-[#374151] to-[#111827]",
    fontStyle: "font-sans font-bold",
  },
  {
    id: "pasteleria-dulces",
    name: "Pastelería & Dulces",
    category: "Reposteria",
    description: "Colores pastel rosa/crema, esquinas redondeadas y ambiente dulce.",
    badge: "Pastel",
    bgClass: "bg-[#fff5f5] text-[#702459]",
    cardClass: "bg-white border-[#fed7e2] shadow-sm rounded-3xl hover:border-[#fbb6ce]",
    primaryBtnClass: "bg-[#d63384] text-white hover:bg-[#b8226d] shadow-md rounded-2xl",
    accentTextClass: "text-[#d63384]",
    headerStyle: "from-[#d63384] to-[#9b1d5e]",
    fontStyle: "font-sans",
  },
  {
    id: "cafe-tostado",
    name: "Café & Obrador Tostado",
    category: "Cafeterías & Tueste",
    description: "Tonos grano de café tostado, fondo madera oscura e iluminación acogedora.",
    badge: "Cálido",
    bgClass: "bg-[#2b1e1a] text-[#f4ebd0]",
    cardClass: "bg-[#3c2a24] border-[#523b33] shadow-md hover:border-[#d4a373]",
    primaryBtnClass: "bg-[#d4a373] text-[#2b1e1a] font-bold hover:bg-[#faedcd]",
    accentTextClass: "text-[#d4a373]",
    headerStyle: "from-[#3c2a24] to-[#1e1310]",
    fontStyle: "font-serif",
  },
  {
    id: "gourmet-delicatessen",
    name: "Gourmet & Delicatessen",
    category: "Delicatessen",
    description: "Fondo negro refinado con acentos dorados para selecciones exclusivas o limitadas.",
    badge: "Premium",
    bgClass: "bg-[#0f0f11] text-[#f0f0f2]",
    cardClass: "bg-[#18181c] border-[#2d2d35] shadow-xl hover:border-[#d4af37]",
    primaryBtnClass: "bg-[#d4af37] text-black font-bold hover:bg-[#f3e5ab] shadow-md shadow-[#d4af37]/20",
    accentTextClass: "text-[#d4af37]",
    headerStyle: "from-[#18181c] to-[#0f0f11]",
    fontStyle: "font-serif tracking-wider",
  },
  {
    id: "pueblo-unido",
    name: "Pueblo Unido & Reparto",
    category: "Comunidad Local",
    description: "Diseño comunitario con aviso gigante del itinerario del vehículo de reparto.",
    badge: "Reparto Local",
    bgClass: "bg-[#edf2f7] text-[#2d3748]",
    cardClass: "bg-white border-[#cbd5e0] shadow-sm hover:border-[#3182ce]",
    primaryBtnClass: "bg-[#3182ce] text-white hover:bg-[#2b6cb0]",
    accentTextClass: "text-[#3182ce]",
    headerStyle: "from-[#3182ce] to-[#2c5282]",
    fontStyle: "font-sans",
  },
  {
    id: "producto-estrella",
    name: "Ficha Producto Estrella",
    category: "Monoproducto",
    description: "Enfoque gigante en 1 o 2 productos del día (ej. Pan de la Casa recién salido).",
    badge: "Destacado",
    bgClass: "bg-[#fffbf0] text-[#4a3b32]",
    cardClass: "bg-white border-[#f6e0b5] shadow-md hover:border-[#e6a100]",
    primaryBtnClass: "bg-[#e6a100] text-white font-extrabold hover:bg-[#c68a00]",
    accentTextClass: "text-[#e6a100]",
    headerStyle: "from-[#e6a100] to-[#b37e00]",
    fontStyle: "font-sans",
  },
  {
    id: "menu-denso",
    name: "Menú Lista Denso",
    category: "Tabla Recurrente",
    description: "Formato lista/tabla compacto ideado para compras semanales o variadas.",
    badge: "Eficiente",
    bgClass: "bg-white text-gray-900",
    cardClass: "bg-gray-50 border-gray-200 shadow-xs hover:border-gray-400",
    primaryBtnClass: "bg-gray-900 text-white hover:bg-black",
    accentTextClass: "text-gray-900",
    headerStyle: "from-gray-800 to-gray-900",
    fontStyle: "font-mono text-sm",
  },
];
